# Generated by Django 4.2.2 on 2024-04-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(default='', max_length=100)),
                ('user_name', models.CharField(default='', max_length=255)),
                ('date', models.DateField()),
                ('leave_type', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
