# Generated by Django 4.2.2 on 2024-04-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelhrapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='days',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
