# Generated by Django 4.2.2 on 2024-04-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelhrapp', '0002_leave_days_alter_leave_leave_type_alter_leave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbusement',
            fields=[
                ('reimbus_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(default='', max_length=100)),
                ('user_name', models.CharField(default='', max_length=255)),
                ('date', models.DateField()),
                ('expense_type', models.CharField(default='', max_length=50)),
                ('amount', models.CharField(default='', max_length=100)),
                ('days', models.CharField(default='', max_length=50)),
                ('shortdesc', models.TextField()),
                ('pdfpath', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
                ('paymenttype', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
