# Generated by Django 4.2.2 on 2024-04-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelhrapp', '0004_employaccdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='employaccdata',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
