# Generated by Django 4.2.2 on 2024-04-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelhrapp', '0005_employaccdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employaccdata',
            name='Communicationvalue',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='employaccdata',
            name='FeedbackScorevalue',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='employaccdata',
            name='Productivityvalue',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='employaccdata',
            name='Satisfactionvalue',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='employaccdata',
            name='Skillsvalue',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
