# Generated by Django 4.2.2 on 2024-04-06 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelhrapp', '0007_leave_llmsuggesstion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='llmsuggesstion',
            new_name='llmsuggest',
        ),
    ]
