# Generated by Django 4.2.2 on 2024-04-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelhrapp', '0009_msgdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employaccdata',
            name='CasualLeavecount',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='employaccdata',
            name='MaternityLeavecount',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='employaccdata',
            name='PrivilegeLeavecount',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='employaccdata',
            name='SickLeavecount',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
