# Generated by Django 4.2.2 on 2024-04-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelhrapp', '0011_chatdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatdata',
        ),
    ]
