# Generated by Django 4.2.2 on 2024-04-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelhrapp', '0013_chatdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='employaccdata',
            name='Checkin',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employaccdata',
            name='Checkout',
            field=models.CharField(default='', max_length=50),
        ),
    ]
